DROP TABLE IF EXISTS player;
DROP TABLE IF EXISTS rank;

CREATE TABLE player (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  SESSIONID TEXT UNIQUE NOT NULL,
  record INTEGER NOT NULL
);

CREATE TABLE rank (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  playername TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);